baseurl = "https://www.mirrormedia.mg/"
languageCode = "zh-tw"
title = "鏡傳媒 Mirror Media"
theme = "mirror"
googleAnalytics = "UA-83609754-1"
disableSitemap = "true"
disableRSS = "true"

[params]
	description = "鏡傳媒以台灣為基地，是一跨平台綜合媒體，包含《鏡週刊》以及下設五大分眾內容的《鏡傳媒》網站，刊載時事、財經、人物、國際、文化、娛樂、美食旅遊、精品鐘錶等深入報導及影音內容。我們以「鏡」為名，務求反映事實、時代與人性。"
	imgBaseUrl = "/story/img"
	cssBaseUrl = "/story/css"
	jsBaseUrl = "/story/js"

[social]
	line		= "https://line.me/R/ti/p/%40cuk1273e"
	weibo		= "http://www.weibo.com/u/6030041924?is_all=1"
	facebook	= "https://www.facebook.com/mirrormediamg/"
	wechat		= "#wechat"
	instagram	= "https://www.instagram.com/mirror_media/"
	feed		= "/story/rss.xml"
	mail		= "mailto:mirror885@mirrormedia.mg"
	book		= "https://goo.gl/forms/g2ny8HzAXTAfwH6I2"

[taxonomies]
	tag = "HugoTags"
	category = "HugoCategories"
