baseurl = "http://www.mirrormedia.mg/"
languageCode = "zh-tw"
title = "鏡傳媒 Mirror Media"
theme = "mirror"
googleAnalytics = "UA-83609754-1"

[params]
	imgBaseUrl = "/story/img"
	cssBaseUrl = "/story/css"
	jsBaseUrl = "/story/js"

[social]
	line		= "#line"
	weibo		= "#weibo"
	facebook	= "http://www.facebook.com/mirrormediamg/"
	wechat		= "#wechat"
	instagram	= "https://www.instagram.com/mirror_media/"
	feed		= "#feed"
	mail		= "#mail"

[taxonomies]
	tag = "HugoTags"
	category = "HugoCategories"
