baseurl = "http://www.mm.mg/"
languageCode = "zh-tw"
title = "MirroMedia"
theme = "mirror"
googleAnalytics = "UA-83609754-1"

[params]
	imgBaseUrl = "/assets/img"
	cssBaseUrl = "/assets/css"
	jsBaseUrl = "/assets/js"

[social]
	line		= "#line"
	weibo		= "#weibo"
	facebook	= "#facebook"
	wechat		= "#wechat"
	instagram	= "#instagram"
	feed		= "#feed"
	mail		= "#mail"

[taxonomies]
	tag = "HugoTags"
	category = "HugoCategories"