baseurl = "http://www.mirrormedia.mg/"
languageCode = "zh-tw"
title = "鏡傳媒 Mirror Media"
theme = "mirror"
googleAnalytics = "UA-83609754-1"

[params]
	imgBaseUrl = "/news/img"
	cssBaseUrl = "/news/css"
	jsBaseUrl = "/news/js"

[social]
	line		= "#line"
	weibo		= "#weibo"
	facebook	= "#facebook"
	wechat		= "#wechat"
	instagram	= "#instagram"
	feed		= "#feed"
	mail		= "#mail"

[taxonomies]
	tag = "HugoTags"
	category = "HugoCategories"