baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "zh-tw"
title = "MirroMedia"
theme = "mirror"
googleAnalytics = "UA-83609754-1"

[params]
imgBaseUrl = "/img"
cssBaseUrl = "/css"
jsBaseUrl = "/js"

[taxonomies]
tag = "HugoTags"
category = "HugoCategories"